---
- name: DNS
  block:
    - name: Read Domain lines and assert
      ansible.builtin.assert:
        that: 
          - "item in ansible_net_config"
        fail_msg: "Line missing. Check for orrective action"
        success_msg: "Line found in current configuration"
      with_items:
        - "{{ ios_domain }}"
      register: dns_check
  rescue:
    - name: Perform Corrective Action when Failed
      cisco.ios.ios_config: 
        lines: "{{ item }}"
      with_items: "{{ ios_domain }}"
    - name: Device fact gathering failure
      ansible.builtin.debug:
        msg: "{{ inventory_hostname }} Failed Validation"
    - ansible.builtin.set_fact:
        check_result:
          host: "{{ inventory_hostname }}"
          status: "FAIL"
          message: "{{ dns_check.results | to_nice_yaml }}"
    - ansible.builtin.lineinfile:
        insertafter: EOF
        dest: "outputs/failure_report.txt"
        line: |
          {{ check_result.host }} 
          {{ check_result.status }} REASON:
          {{ check_result.message }} 
  always:
    - name: Continue to next check
      debug:
        msg: "Continue to AAA and TACACS"

- name: AAA and TACACS
  block:
    - name: Read AAA lines and assert
      ansible.builtin.assert:
        that: 
          - "item in ansible_net_config"
        fail_msg: "Line missing. Check for orrective action"
        success_msg: "Line found in current configuration"
      with_items:
        - "{{ ios_aaa_tacacs }}"
      register: aaa_check
  rescue:
    #- name: Perform Corrective Action when Failed
    #  cisco.ios.ios_config: 
    #    lines: "{{ item }}"
    #  with_items: "{{ ios_aaa_tacacs }}"
    - name: Device fact gathering failure
      ansible.builtin.debug:
        msg: "{{ inventory_hostname }} Failed Validation"
    - ansible.builtin.set_fact:
        check_result:
          host: "{{ inventory_hostname }}"
          status: "FAIL"
          message: "{{ aaa_check.results | to_nice_yaml }}"
    - ansible.builtin.lineinfile:
        insertafter: EOF
        dest: "outputs/failure_report.txt"
        line: |
          ---
          {{ check_result.host }} 
          {{ check_result.status }} REASON:
          {{ check_result.message }} 
  always:
    - name: Continue to Completed
      debug:
        msg: "Continue to NTP"

- name: NTP
  block:
    - name: Read NTP lines and assert
      ansible.builtin.assert:
        that: 
          - "item in ansible_net_config"
        fail_msg: "Line missing. Check for orrective action"
        success_msg: "Line found in current configuration"
      with_items:
        - "{{ ios_ntp }}"
      register: ntp_check
  rescue:
    #- name: Perform Corrective Action when Failed
    #  cisco.ios.ios_config: 
    #    lines: "{{ item }}"
    #  with_items: "{{ ios_ntp }}"
    - name: Device fact gathering failure
      ansible.builtin.debug:
        msg: "{{ inventory_hostname }} Failed Validation"
    - ansible.builtin.set_fact:
        check_result:
          host: "{{ inventory_hostname }}"
          status: "FAIL"
          message: "{{ ntp_check.results | to_nice_yaml }}"
    - ansible.builtin.lineinfile:
        insertafter: EOF
        dest: "outputs/failure_report.txt"
        line: |
          ---
          {{ check_result.host }} 
          {{ check_result.status }} REASON:
          {{ check_result.message }} 
  always:
    - name: Continue to Completed
      import_tasks: import_tasks/completed_tests.yml
...