---
# Validation Playbook / Task Caller
# Author: Jose Rosa
- name: compliance validation
  hosts: cisco
  order: shuffle
  gather_facts: false
  serial: 50

  vars_files:
    - './vars/policies.yml'

  tasks:
    - name: Include Authentication Tasks
      ansible.builtin.import_tasks: imported_tasks/default-authentication-tasks.yml

    - block:
        - name: Process Config File
          cisco.ios.ios_facts:
            gather_subset: config
          register: device_cfg
      rescue:
        - name: Log Error
          debug:
            msg: "{{ device_cfg['msg'] }}"

    - ansible.builtin.import_tasks: imported_tasks/check_policies.yml
...